receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317

exporters:
  prometheus:
    endpoint: otel-collector:8889
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

processors:
  batch:

extensions:
  health_check:
    endpoint: otel-collector:13133

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      # processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      exporters: [zipkin]